### PR TITLE
Split dirs

### PR DESCRIPTION
**Pull request by SimonCropp**
- remove `Exclude` from config file and replace with `ExcludeDirectories`
 - remove `exclude` from command line options and replace with `exclude-directories`
 - Add `exclude-markdown-directories` to command line options
 - Add `ExcludeMarkdownDirectories` to config file
 - Add `exclude-snippet-directories` to command line options
 - Add `ExcludeSnippetDirectories` to config file

### CODE REVIEW

**Comment by claremacrae** [comment]
Hi Simon, what does "Split dirs" mean, please - from a user perspective?

**Comment by SimonCropp** [comment]
@claremacrae  updated

**Comment by claremacrae** [comment]
Thanks... "so that directories can be excluded from markdown or snippet scanning specifically" clarified it a lot...

A few thoughts...

1. So now I understand why I got the error message "Failed: `Exclude` is obsolete. Use `ExcludeDirectories`." when I updated... 

    At that point, I had no memory that Exclude was a command-line argument or something in the config. So didn't know where to look for Exclude to change it.

2. I'm curious about the PR that you submitted to ApprovalTests.cpp - I think it was a breaking change to stop mdsnippets working in that project, without updating the projects mdsnippets.json at the same time?

3. When releases have breaking changes, it's really helpful if this is specifically highlighted in the release notes, explicitly pointing users to what they may have to change (the config file or any scripts invoking mdsnippets, in this case).

4. I had a look to see how many projects would be affected by this potentially breaking change...

    These are the ones where mdsnippets.json contains exclude... https://github.com/search?l=&p=2&q=exclude+filename%3Amdsnippets.json&type=Code

    At the moment, it's only 17 hits, one or two of which are either your docs, or ones that have been updated already.

5. A similar search for scripts that invoke mdsnippets on the command line might show extra cases that will need updating at some point.

    Having said that, I think this search suggests there are no such cases: https://github.com/search?q=mdsnippets+exclude&type=code

6. In this case, I personally would have opted to maintain backwards compatibility, keeping the old arguments working... 

7. I'm now going to have to submit PRs today updating the config of projects that I added mdsnippets to - like [Catch2](https://github.com/catchorg/Catch2/blob/40b9df567f2a9ff09e3938bf2005413640eace9f/mdsnippets.json)....  As a user, it's changes like this that would make me more likely to pin to a known-working version...

**Comment by SimonCropp** [comment]
> At that point, I had no memory that Exclude was a command-line argument or something in the config. So didn't know where to look for Exclude to change it.

agreed

https://github.com/SimonCropp/MarkdownSnippets/commit/9bb76000f54181fd04d0bcc7f76cac03aaf98d08

**Comment by SimonCropp** [comment]
> I think it was a breaking change to stop mdsnippets working in that project, without updating the projects mdsnippets.json at the same time?

I did it to several repos, i was planning on coming back and seeing if the build broke

**Comment by SimonCropp** [comment]
.> In this case, I personally would have opted to maintain backwards compatibility, keeping the old arguments working.

normally i would as well, but i could not figure out a way of communicating that the old setting is obsolete, while suggesting to use the new config. and that would result in needing to keep the extra code around forever.

**Comment by SimonCropp** [comment]
@claremacrae

> I'm now going to have to submit PRs today updating the config of projects that I added mdsnippets to - like Catch2.... As a user, it's changes like this that would make me more likely to pin to a known-working version...

sorry for the hassle. I did no think changing `Exclude` to `ExcludeDirectories` in a ~5 line config file was a significant impact. and hence did not put too much effort into the transition

**Comment by claremacrae** [comment]
> 4. I had a look to see how many projects would be affected by this potentially breaking change...
>    These are the ones where mdsnippets.json contains exclude... https://github.com/search?l=&p=2&q=exclude+filename%3Amdsnippets.json&type=Code
>    At the moment, it's only 17 hits, one or two of which are either your docs, or ones that have been updated already.

This is a better search: [exclude NOT ExcludeDirectories  filename:mdsnippets.json](https://github.com/search?q=exclude+NOT+ExcludeDirectories++filename%3Amdsnippets.json&type=Code&ref=advsearch&l=&l=), as it excludes projects already updated...

Note to self: It doesn't find files in any outstanding pull requests that wish to add mdsnippets to projects - but I've only got one of those...

**Comment by claremacrae** [comment]
I've updated all mine, and put in pull requests:

* https://github.com/emilybache/Recently-Used-List-Docs/pull/1
* https://github.com/LesleyLai/eml/pull/2
* https://github.com/approvals/ApprovalTests.Python/pull/94
* https://github.com/catchorg/Catch2/pull/2173

**Comment by claremacrae** [comment]
> @claremacrae
> 
> > I think it was a breaking change to stop mdsnippets working in that project, without updating the projects mdsnippets.json at the same time?
> 
> I did it to several repos, i was planning on coming back and seeing if the build broke

Thanks.. Yes, that would work for the ones that have a CI build to auto-regenerate the docs... Others would have found out next time they updated manually.

**Comment by claremacrae** [comment]
> sorry for the hassle. I did no think changing `Exclude` to `ExcludeDirectories` in a ~5 line config file was a significant impact. and hence did not put too much effort into the transition

Thanks - and sorry too for my rather long, grumpy message!

mdsnippets is a great tool, but I do feel slightly responsible for its users, having done a few lighting talks to encourage people to use it!

**Comment by SimonCropp** [comment]
@claremacrae 

As an aside: if i do break things, please feel free to ping me to fix them in the target repo.

**Comment by SimonCropp** [comment]
@claremacrae BTW if u want update to the current "non breaking changes version"

```
dotnet tool update --global MarkdownSnippets.Tool --version 23.*
```

**Comment by claremacrae** [comment]
> @claremacrae
> 
> As an aside: if i do break things, please feel free to ping me to fix them in the target repo.

Hi Simon, that's really kind - thanks...

Part of this is definition of breaking change.. For most users, as long as the tool still runs and updates their code, it doesn't matter if the hidden HTML content changes, and so they wouldn't qualify as breaking changes...

For ApprovalTests.cpp, and a couple of related projects, I post-process the generated .md files, to convert them to Restructured Text and feed them to Sphinx - for publishing at e.g. https://approvaltestscpp.readthedocs.io/en/latest/

This post-processing code is very sensitive to changes in mdsnippet's HTML output, and the code is Python, which I wouldn't expect you to maintain!

Some example munging code:

https://github.com/approvals/ApprovalTests.cpp/blob/7a8fe07e66d51d9a19ef490d9d5262c97505e2c0/doc/sphinx/markdown_conversion.py#L89-L115

**Pull request merged**
