### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by JayBazuzi**

### CODE REVIEW

**Comment by claremacrae** [comment]
Here is an example header:

```markdown
<!--
This file was generate by MarkdownSnippets.
Source File: /doc/mdsource/ApprovalTestingConcept.source.md
To change this file edit the source file and then re-run the generation using either the dotnet global tool (https://github.com/SimonCropp/MarkdownSnippets#markdownsnippetstool) or using the api (https://github.com/SimonCropp/MarkdownSnippets#running-as-a-unit-test).
-->
```

When someone edits the generated document by mistake, e.g. on github page when they edit directly, I like that the `Source File:` label and file name is at the start of a line. This means that information stands out clearly.

**Comment by claremacrae** [comment]
This fix seems to run the first and second lines together.

Having used this tool for a while now, I would prefer that separation to be retained, so that "Source File" is at the start of a line.

I don't have an opinion about whether it needs to be Markdown or not, though I think it's a bit confusing to have Markdown inside `<!-- -->`

**Comment by JayBazuzi** [comment]
What about making the first line say something like `GENERATED FILE - DO NOT EDIT`?

**Comment by claremacrae** [comment]
I don't understand what actual, practical problem you are trying to solve?
The current text works really well in practice - it's very clear.

**Comment by claremacrae** [comment]
Yes, `GENERATED FILE - DO NOT EDIT` would be a nice addition.

And fixing the harmless typo in `was generate by` - which I hadn't noticed until this PR - would be fine too...

**Comment by SimonCropp** [comment]
Happy with the “GENERATED...” and the typp fix. But i don’t really understand the markdown links? In what context would those be rendered so as to make them being markdown useful?

The reason the source file was on its own line is to favour vertical scroll over horizontal scroll. Make it easier to groc when reviewing, and also makes it more mobile friendly

**Comment by SimonCropp** [comment]
merged manually

**Pull request closed without merging**
