### PR TITLE
Minor corrections to docs - this updated the table of contents

### PR DESCRIPTION
**Pull request by claremacrae**
Note also that there is a stray line `Then snippets with that key.` that perhaps doesn't make sense - well, at least to me...

### CODE REVIEW

**Comment by SimonCropp** [comment]
thanks :)

**Comment by SimonCropp** [comment]
and the difference in the toc was from this feature. https://github.com/SimonCropp/MarkdownSnippets#ignore-headings  i was running a beta with those headings excluded. i have since deployed that in a stable

**Comment by claremacrae** [comment]
Trivia, but I'm curious why would you want to exclude those headings from the ToC? I'm probability a bit of a purist, but it confused me that some headings were missing...

One possibility to keep the ToC short would be to use something like this - to add a new L2 heading and demote the 3 you exclude to L3:

```markdown
## Releases and Credits

### Release Notes
...
### Credits
...
### Icon
...
```

**Comment by SimonCropp** [comment]
a toc on a readme takes a lot of space above the fold. i would prefer to minimise that space

**Pull request merged**
