### PR TITLE
Fix endSnippet block getting removed for missing snippet

### PR DESCRIPTION
**Pull request by mysticmind**
- Fix endSnippet block getting removed for a missing snippet with
config InPlaceOverwrite
- Wrap `** Count not find snippet...` in a fenced code block.

### CODE REVIEW

**Comment by mysticmind** [comment]
The problem is outlined below:
In markdown, the following is the content with InPlaceOverwrite:
```
<!-- snippet: sample_FindJsonUserByUsername -->
<!-- endSnippet -->
```

When I run mdsnippets tool or via msbuild for a missing snippet, it strips off `<!-- endSnippet -->`

This PR fixes the same.

**Comment by SimonCropp** [comment]
can u add a test to verify this change

**Comment by mysticmind** [comment]
> I couldn't figure out a way to add unit tests for this case, please provide some clues, I will try to add the same.

I had added the above in my comment, still checking to see how to add a unit test.

**Comment by mysticmind** [comment]
@SimonCropp  I am closing this PR for now. I am able to reproduce the issue using the latest NuGet version 23.1.3. But not on the latest codebase on Git.

**Comment by mysticmind** [comment]
I was able to reproduce this in the latest code in repo, I am committing the test shortly for your review.

**Comment by mysticmind** [comment]
@SimonCropp the PR is ready for your review and next steps. Also it would be super helpful if you could release it to NuGet at the earliest. Thank you!

**Comment by SimonCropp** [comment]
thanks. deployed

**Pull request merged**
